<script lang="ts" setup>
import {
  Search,
  Rss,
  SlidersHorizontal,
  MapPin,
  Terminal,
  AtSign,
  IdCard,
  Mail,
  Network,
  PenTool,
  Hourglass,
  ArrowRight,
  ArrowUpRight,
  Star,
  Clock,
  Database,
  BookOpen,
  Activity,
  CheckCircle,
  Bookmark,
  Share,
  Camera,
  ChevronRight,
  Menu,
  X,
  ArrowLeft,
  MoreHorizontal,
  Edit,
  LayoutDashboard,
  Settings,
  Image as ImageIcon,
  LogOut,
  FileText,
  ChevronDown,
  Check,
  Lock,
  Shield,
  Eye,
  Send,
  Filter,
  Fingerprint,
  MailCheck,
  MonitorSmartphone,
  TrendingUp,
  Leaf,
  Users,
  Trash2,
  Tags,
  Folder,
} from "@lucide/vue";

interface Props {
  name: string;
  class?: string;
}

const iconMap: Record<string, any> = {
  search: Search,
  rss_feed: Rss,
  tune: SlidersHorizontal,
  pin_drop: MapPin,
  terminal: Terminal,
  alternate_email: AtSign,
  badge: IdCard,
  mail: Mail,
  hub: Network,
  architecture: PenTool,
  hourglass_empty: Hourglass,
  arrow_forward: ArrowRight,
  north_east: ArrowUpRight,
  star: Star,
  lock_clock: Clock,
  dataset: Database,
  auto_stories: BookOpen,
  monitoring: Activity,
  verified: CheckCircle,
  bookmark_border: Bookmark,
  bookmark: Bookmark,
  share: Share,
  photo_camera: Camera,
  eco: Leaf,
  local_florist: Leaf,
  edit_note: Edit,
  arrow_back: ArrowLeft,
  more_horiz: MoreHorizontal,
  dashboard: LayoutDashboard,
  settings: Settings,
  perm_media: ImageIcon,
  logout: LogOut,
  file_text: FileText,
  expand_more: ChevronDown,
  check: Check,
  lock_open: Lock,
  security_key: Shield,
  visibility: Eye,
  send: Send,
  fingerprint: Fingerprint,
  mark_email_read: MailCheck,
  manage_search: Filter,
  memory: MonitorSmartphone,
  nature_people: Users,
  trending_up: TrendingUp,
  chevron_right: ChevronRight,
  west: ArrowLeft,
  east: ArrowRight,
  folder: Folder,
  tags: Tags,
  delete: Trash2,
  x: X,
};

// props
const props = defineProps<Props>();
const iconComponent = computed(() => iconMap[props.name] || Star);
</script>

<template>
  <component :is="iconComponent" :class="props.class" />
</template>
